<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BacSiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('bac_sis')->truncate();

        DB::table('bac_sis')->insert([
            [
                'id' => 1,
                'ho_ten' => 'Bác sĩ Nguyễn Văn An',
                'email' => 'bs.nguyenvanan@example.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234567',
                'ngay_sinh' => '1980-05-15',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ chuyên khoa tim mạch với hơn 15 năm kinh nghiệm',
                'hinh_anh' => 'https://randomuser.me/api/portraits/men/1.jpg',
                'chuc_danh' => 'Bác sĩ chính',
                'so_nam_kinh_nghiem' => '15',
                'kinh_nghiem_lam_viec' => 'Bệnh viện Bạch Mai',
                'qua_trinh_dao_tao' => 'ĐH Y Hà Nội',
                'chung_chi' => 'Chứng chỉ tim mạch học',
                'thanh_tuu' => 'Nghiên cứu về điều trị suy tim',
                'thanh_vien_to_chuc' => 'Hội Tim mạch Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 5000, // Tim mạch
            ],
            [
                'id' => 2,
                'ho_ten' => 'Bác sĩ Trần Thị Bình',
                'email' => 'bs.tranthibinh@example.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234568',
                'ngay_sinh' => '1985-08-20',
                'gioi_tinh' => 0,
                'mo_ta' => 'Bác sĩ chuyên khoa da liễu, chuyên điều trị các bệnh về da',
                'hinh_anh' => 'https://randomuser.me/api/portraits/women/2.jpg',
                'chuc_danh' => 'Thạc sĩ',
                'so_nam_kinh_nghiem' => '12',
                'kinh_nghiem_lam_viec' => 'Bệnh viện Da liễu Trung ương',
                'qua_trinh_dao_tao' => 'ĐH Y TP.HCM',
                'chung_chi' => 'Chứng chỉ da liễu học',
                'thanh_tuu' => 'Điều trị thành công nhiều ca bệnh hiếm gặp',
                'thanh_vien_to_chuc' => 'Hội Da liễu Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 2,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 3500, // Da liễu
            ],
            [
                'id' => 3,
                'ho_ten' => 'Bác sĩ Lê Văn Cường',
                'email' => 'bs.levancuong@example.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234569',
                'ngay_sinh' => '1978-12-10',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ chuyên khoa nội tổng hợp, có kinh nghiệm điều trị nhiều loại bệnh',
                'hinh_anh' => 'https://randomuser.me/api/portraits/men/3.jpg',
                'chuc_danh' => 'Tiến sĩ',
                'so_nam_kinh_nghiem' => '20',
                'kinh_nghiem_lam_viec' => 'Bệnh viện Việt Đức',
                'qua_trinh_dao_tao' => 'ĐH Y Hà Nội',
                'chung_chi' => 'Chứng chỉ nội khoa',
                'thanh_tuu' => 'Nhiều công trình nghiên cứu về bệnh tiểu đường',
                'thanh_vien_to_chuc' => 'Hội Nội khoa Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 3,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 5000, // Nội tổng quát - Tiến sĩ
            ],
            [
                'id' => 4,
                'ho_ten' => 'Bác sĩ Phạm Thị Dung',
                'email' => 'bs.phamthidung@example.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234570',
                'ngay_sinh' => '1982-03-25',
                'gioi_tinh' => 0,
                'mo_ta' => 'Bác sĩ chuyên khoa nhi, chuyên điều trị các bệnh ở trẻ em',
                'hinh_anh' => 'https://randomuser.me/api/portraits/women/4.jpg',
                'chuc_danh' => 'Bác sĩ chính',
                'so_nam_kinh_nghiem' => '14',
                'kinh_nghiem_lam_viec' => 'Bệnh viện Nhi Trung ương',
                'qua_trinh_dao_tao' => 'ĐH Y Hà Nội',
                'chung_chi' => 'Chứng chỉ nhi khoa',
                'thanh_tuu' => 'Điều trị thành công nhiều ca bệnh nhi phức tạp',
                'thanh_vien_to_chuc' => 'Hội Nhi khoa Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 4,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 4000, // Nhi khoa
            ],
            [
                'id' => 5,
                'ho_ten' => 'Bác sĩ Vũ Hoàng Nam',
                'email' => 'bs.vuhoangnam@example.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234571',
                'ngay_sinh' => '1987-07-08',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ chuyên khoa mắt, chuyên điều trị các bệnh về mắt',
                'hinh_anh' => 'https://randomuser.me/api/portraits/men/5.jpg',
                'chuc_danh' => 'Thạc sĩ',
                'so_nam_kinh_nghiem' => '10',
                'kinh_nghiem_lam_viec' => 'Bệnh viện Mắt Trung ương',
                'qua_trinh_dao_tao' => 'ĐH Y TP.HCM',
                'chung_chi' => 'Chứng chỉ nhãn khoa',
                'thanh_tuu' => 'Thực hiện nhiều ca phẫu thuật mắt thành công',
                'thanh_vien_to_chuc' => 'Hội Nhãn khoa Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 5,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 3000, // Mắt
            ],
            [
                'id' => 6,
                'ho_ten' => 'Bác sĩ Hoàng Thị Mai',
                'email' => 'bs.hoangthimai@example.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234572',
                'ngay_sinh' => '1983-06-12',
                'gioi_tinh' => 0,
                'mo_ta' => 'Bác sĩ chuyên khoa sản phụ khoa, chuyên về khám thai và điều trị bệnh phụ khoa',
                'hinh_anh' => 'https://randomuser.me/api/portraits/women/6.jpg',
                'chuc_danh' => 'Bác sĩ chính',
                'so_nam_kinh_nghiem' => '16',
                'kinh_nghiem_lam_viec' => 'Bệnh viện Từ Dũ',
                'qua_trinh_dao_tao' => 'ĐH Y Hà Nội',
                'chung_chi' => 'Chứng chỉ sản phụ khoa',
                'thanh_tuu' => 'Thực hiện nhiều ca sinh mổ thành công',
                'thanh_vien_to_chuc' => 'Hội Sản phụ khoa Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 1,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 4500, // Sản phụ khoa
            ],
            [
                'id' => 7,
                'ho_ten' => 'Bác sĩ Đặng Văn Hùng',
                'email' => 'bs.dangvanhung@example.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234573',
                'ngay_sinh' => '1979-09-18',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ chuyên khoa thần kinh, chuyên điều trị các bệnh về não và hệ thần kinh',
                'hinh_anh' => 'https://randomuser.me/api/portraits/men/7.jpg',
                'chuc_danh' => 'Tiến sĩ',
                'so_nam_kinh_nghiem' => '18',
                'kinh_nghiem_lam_viec' => 'Bệnh viện 108',
                'qua_trinh_dao_tao' => 'ĐH Y Hà Nội',
                'chung_chi' => 'Chứng chỉ thần kinh học',
                'thanh_tuu' => 'Nghiên cứu về điều trị đột quỵ',
                'thanh_vien_to_chuc' => 'Hội Thần kinh Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 2,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 3800, // Giá mặc định
            ],
            [
                'id' => 8,
                'ho_ten' => 'Bác sĩ Ngô Thị Lan',
                'email' => 'bs.ngothilan@example.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234574',
                'ngay_sinh' => '1986-04-30',
                'gioi_tinh' => 0,
                'mo_ta' => 'Bác sĩ chuyên khoa răng hàm mặt, chuyên về nha khoa thẩm mỹ',
                'hinh_anh' => 'https://randomuser.me/api/portraits/women/8.jpg',
                'chuc_danh' => 'Thạc sĩ',
                'so_nam_kinh_nghiem' => '11',
                'kinh_nghiem_lam_viec' => 'Bệnh viện Răng Hàm Mặt Trung ương',
                'qua_trinh_dao_tao' => 'ĐH Y TP.HCM',
                'chung_chi' => 'Chứng chỉ răng hàm mặt',
                'thanh_tuu' => 'Thực hiện nhiều ca phẫu thuật thẩm mỹ thành công',
                'thanh_vien_to_chuc' => 'Hội Răng Hàm Mặt Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 3,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 3800, // Giá mặc định
            ],
            [
                'id' => 9,
                'ho_ten' => 'Bác sĩ Lý Văn Tài',
                'email' => 'bs.lyvantai@example.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234575',
                'ngay_sinh' => '1981-11-05',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ chuyên khoa xương khớp, chuyên điều trị các bệnh về cơ xương khớp',
                'hinh_anh' => 'https://randomuser.me/api/portraits/men/9.jpg',
                'chuc_danh' => 'Bác sĩ chính',
                'so_nam_kinh_nghiem' => '17',
                'kinh_nghiem_lam_viec' => 'Bệnh viện Chợ Rẫy',
                'qua_trinh_dao_tao' => 'ĐH Y TP.HCM',
                'chung_chi' => 'Chứng chỉ xương khớp học',
                'thanh_tuu' => 'Điều trị thành công nhiều ca thoát vị đĩa đệm',
                'thanh_vien_to_chuc' => 'Hội Xương khớp Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 4,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 3800, // Giá mặc định
            ],
            [
                'id' => 10,
                'ho_ten' => 'Bác sĩ Trịnh Thị Hương',
                'email' => 'bs.trinhthihuong@example.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234576',
                'ngay_sinh' => '1984-02-14',
                'gioi_tinh' => 0,
                'mo_ta' => 'Bác sĩ chuyên khoa tâm thần, chuyên điều trị các rối loạn tâm thần',
                'hinh_anh' => 'https://randomuser.me/api/portraits/women/10.jpg',
                'chuc_danh' => 'Thạc sĩ',
                'so_nam_kinh_nghiem' => '13',
                'kinh_nghiem_lam_viec' => 'Bệnh viện Tâm thần Trung ương',
                'qua_trinh_dao_tao' => 'ĐH Y Hà Nội',
                'chung_chi' => 'Chứng chỉ tâm thần học',
                'thanh_tuu' => 'Điều trị thành công nhiều ca trầm cảm',
                'thanh_vien_to_chuc' => 'Hội Tâm thần Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 5,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 3800, // Giá mặc định
            ],
            [
                'id' => 11,
                'ho_ten' => 'Bác sĩ Võ Văn Thành',
                'email' => 'bs.vovanthanh@example.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234577',
                'ngay_sinh' => '1988-12-25',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ chuyên khoa ung bướu, chuyên điều trị các bệnh ung thư',
                'hinh_anh' => 'https://randomuser.me/api/portraits/men/11.jpg',
                'chuc_danh' => 'Bác sĩ chính',
                'so_nam_kinh_nghiem' => '9',
                'kinh_nghiem_lam_viec' => 'Bệnh viện K',
                'qua_trinh_dao_tao' => 'ĐH Y Hà Nội',
                'chung_chi' => 'Chứng chỉ ung bướu học',
                'thanh_tuu' => 'Điều trị thành công nhiều ca ung thư giai đoạn sớm',
                'thanh_vien_to_chuc' => 'Hội Ung bướu Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 3800, // Giá mặc định
            ],
            [
                'id' => 12,
                'ho_ten' => 'Bác sĩ Đỗ Thị Nga',
                'email' => 'bs.dothinga@example.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234578',
                'ngay_sinh' => '1983-07-22',
                'gioi_tinh' => 0,
                'mo_ta' => 'Bác sĩ chuyên khoa hô hấp, chuyên điều trị các bệnh về phổi',
                'hinh_anh' => 'https://randomuser.me/api/portraits/women/12.jpg',
                'chuc_danh' => 'Thạc sĩ',
                'so_nam_kinh_nghiem' => '15',
                'kinh_nghiem_lam_viec' => 'Bệnh viện Phổi Trung ương',
                'qua_trinh_dao_tao' => 'ĐH Y TP.HCM',
                'chung_chi' => 'Chứng chỉ hô hấp học',
                'thanh_tuu' => 'Điều trị thành công nhiều ca lao phổi',
                'thanh_vien_to_chuc' => 'Hội Hô hấp Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 2,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 3800, // Giá mặc định
            ],
            [
                'id' => 13,
                'ho_ten' => 'Bác sĩ Bùi Văn Minh',
                'email' => 'bs.buivanminh@example.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234579',
                'ngay_sinh' => '1980-03-08',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ chuyên khoa tiêu hóa, chuyên điều trị các bệnh về đường tiêu hóa',
                'hinh_anh' => 'https://randomuser.me/api/portraits/men/13.jpg',
                'chuc_danh' => 'Tiến sĩ',
                'so_nam_kinh_nghiem' => '19',
                'kinh_nghiem_lam_viec' => 'Bệnh viện Bạch Mai',
                'qua_trinh_dao_tao' => 'ĐH Y Hà Nội',
                'chung_chi' => 'Chứng chỉ tiêu hóa học',
                'thanh_tuu' => 'Nghiên cứu về điều trị viêm loét dạ dày',
                'thanh_vien_to_chuc' => 'Hội Tiêu hóa Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 3,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 3800, // Giá mặc định
            ],
            [
                'id' => 14,
                'ho_ten' => 'Bác sĩ Lê Thị Kim',
                'email' => 'bs.lethikim@example.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234580',
                'ngay_sinh' => '1985-10-16',
                'gioi_tinh' => 0,
                'mo_ta' => 'Bác sĩ chuyên khoa nội tiết, chuyên điều trị các bệnh về tuyến nội tiết',
                'hinh_anh' => 'https://randomuser.me/api/portraits/women/14.jpg',
                'chuc_danh' => 'Bác sĩ chính',
                'so_nam_kinh_nghiem' => '12',
                'kinh_nghiem_lam_viec' => 'Bệnh viện Nội tiết Trung ương',
                'qua_trinh_dao_tao' => 'ĐH Y Hà Nội',
                'chung_chi' => 'Chứng chỉ nội tiết học',
                'thanh_tuu' => 'Điều trị thành công nhiều ca tiểu đường',
                'thanh_vien_to_chuc' => 'Hội Nội tiết Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 4,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 3800, // Giá mặc định
            ],
            [
                'id' => 15,
                'ho_ten' => 'Bác sĩ Phan Văn Dũng',
                'email' => 'bs.phanvandung@example.com',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0901234581',
                'ngay_sinh' => '1987-01-28',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ chuyên khoa cấp cứu, chuyên xử lý các trường hợp cấp cứu',
                'hinh_anh' => 'https://randomuser.me/api/portraits/men/15.jpg',
                'chuc_danh' => 'Thạc sĩ',
                'so_nam_kinh_nghiem' => '10',
                'kinh_nghiem_lam_viec' => 'Bệnh viện Bạch Mai',
                'qua_trinh_dao_tao' => 'ĐH Y Hà Nội',
                'chung_chi' => 'Chứng chỉ cấp cứu học',
                'thanh_tuu' => 'Cứu sống nhiều ca nguy kịch',
                'thanh_vien_to_chuc' => 'Hội Cấp cứu Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 5,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 3000, // Cấp cứu
            ],
        ]);
    }
}
