<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BenhNhanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('benh_nhans')->truncate();

        DB::table('benh_nhans')->insert([
            [
                'ho_ten' => 'Phạm Quốc Khánh',
                'email' => 'phamquockhanh@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234001',
                'ngay_sinh' => '1990-05-15',
                'gioi_tinh' => 1,
                'dia_chi' => '123 Đường Trần Duy Hưng, Cầu Giấy, Hà Nội',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Đoàn Thu Hà',
                'email' => 'doanthuha@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hhttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234002',
                'ngay_sinh' => '1985-08-20',
                'gioi_tinh' => 0,
                'dia_chi' => '456 Nguyễn Trãi, Quận 1, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Nguyễn Đức Huy',
                'email' => 'nguyenduchuy@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234003',
                'ngay_sinh' => '1978-12-10',
                'gioi_tinh' => 1,
                'dia_chi' => '789 Lê Lợi, TP. Huế',
                'tinh_trang' => 1,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Vũ Thị Hương',
                'email' => 'vuthihuong@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hhttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234004',
                'ngay_sinh' => '1982-03-25',
                'gioi_tinh' => 0,
                'dia_chi' => '25 Nguyễn Văn Cừ, Ninh Kiều, Cần Thơ',
                'tinh_trang' => 1,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Trần Minh Khoa',
                'email' => 'tranminhkhoa@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234005',
                'ngay_sinh' => '1987-07-08',
                'gioi_tinh' => 1,
                'dia_chi' => '90 Nguyễn Văn Linh, Đà Nẵng',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Lưu Thảo My',
                'email' => 'luuthaomy@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hhttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234006',
                'ngay_sinh' => '1983-06-12',
                'gioi_tinh' => 0,
                'dia_chi' => '12 Đại Lộ Bình Dương, Thủ Dầu Một',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Phạm Ngọc Anh',
                'email' => 'phamngocanh@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234007',
                'ngay_sinh' => '1979-09-18',
                'gioi_tinh' => 1,
                'dia_chi' => '15 Lê Hồng Phong, Vũng Tàu',
                'tinh_trang' => 1,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Bùi Nhật Quang',
                'email' => 'buinhatquang@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hhttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234008',
                'ngay_sinh' => '1986-04-30',
                'gioi_tinh' => 0,
                'dia_chi' => '100 Cầu Đất, Hải Phòng',
                'tinh_trang' => 1,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Đặng Thanh Tâm',
                'email' => 'dangthanhtam@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234009',
                'ngay_sinh' => '1981-11-05',
                'gioi_tinh' => 1,
                'dia_chi' => '99 Trần Phú, TP. Nha Trang',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Lý Thu Trang',
                'email' => 'lythutrang@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234010',
                'ngay_sinh' => '1984-02-14',
                'gioi_tinh' => 0,
                'dia_chi' => '30 Lý Thường Kiệt, Buôn Ma Thuột',
                'tinh_trang' => 1,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Tạ Quốc Việt',
                'email' => 'taquocviet@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234011',
                'ngay_sinh' => '1988-12-25',
                'gioi_tinh' => 1,
                'dia_chi' => '45 Lê Duẩn, TP. Đà Lạt',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Trương Thị Mỹ Linh',
                'email' => 'truongthimylinh@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234012',
                'ngay_sinh' => '1983-07-22',
                'gioi_tinh' => 0,
                'dia_chi' => '67 Trần Hưng Đạo, TP. Hạ Long',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Ngô Đức Long',
                'email' => 'ngoduclong@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234013',
                'ngay_sinh' => '1980-03-08',
                'gioi_tinh' => 1,
                'dia_chi' => '89 Nguyễn Huệ, TP. Biên Hòa',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Đinh Thị Thuỷ',
                'email' => 'dinhthithuy@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234014',
                'ngay_sinh' => '1985-10-16',
                'gioi_tinh' => 0,
                'dia_chi' => '123 Lý Thường Kiệt, TP. Thủ Dầu Một',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Nguyễn Tuấn Kiệt',
                'email' => 'nguyentuanhiet@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234015',
                'ngay_sinh' => '1987-01-28',
                'gioi_tinh' => 1,
                'dia_chi' => '456 Võ Văn Tần, Quận 3, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Mai Thị Ngọc',
                'email' => 'maithingoc@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234016',
                'ngay_sinh' => '1992-04-05',
                'gioi_tinh' => 0,
                'dia_chi' => '789 Điện Biên Phủ, Quận Bình Thạnh, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Phùng Gia Bảo',
                'email' => 'phunggiabao@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234017',
                'ngay_sinh' => '1986-11-12',
                'gioi_tinh' => 1,
                'dia_chi' => '321 Cách Mạng Tháng 8, Quận 10, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Đoàn Thanh Nhàn',
                'email' => 'doanthanhnhan@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234018',
                'ngay_sinh' => '1989-08-30',
                'gioi_tinh' => 0,
                'dia_chi' => '654 Nguyễn Thị Minh Khai, Quận 1, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Tôn Minh Phúc',
                'email' => 'tonminhphuc@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234019',
                'ngay_sinh' => '1984-06-18',
                'gioi_tinh' => 1,
                'dia_chi' => '987 Lê Văn Việt, Quận 9, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Phạm Ngọc Bích',
                'email' => 'phamngocbich@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234020',
                'ngay_sinh' => '1991-03-22',
                'gioi_tinh' => 0,
                'dia_chi' => '147 Phan Văn Trị, Quận 5, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Lê Văn Thành',
                'email' => 'levanthanh@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234021',
                'ngay_sinh' => '1988-07-14',
                'gioi_tinh' => 1,
                'dia_chi' => '258 Nguyễn Văn Cừ, Quận 1, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Trần Thị Hoa',
                'email' => 'tranthihoa@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234022',
                'ngay_sinh' => '1993-12-03',
                'gioi_tinh' => 0,
                'dia_chi' => '369 Lê Văn Sỹ, Quận 3, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Nguyễn Minh Tuấn',
                'email' => 'nguyenminhtuan@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234023',
                'ngay_sinh' => '1985-09-18',
                'gioi_tinh' => 1,
                'dia_chi' => '147 Võ Thị Sáu, Quận 3, TP.HCM',
                'tinh_trang' => 0,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Hoàng Thị Lan',
                'email' => 'hoangthilan@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234024',
                'ngay_sinh' => '1990-04-25',
                'gioi_tinh' => 0,
                'dia_chi' => '258 Trần Hưng Đạo, Quận 1, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Vũ Đình Phúc',
                'email' => 'vudinhphuc@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234025',
                'ngay_sinh' => '1987-11-08',
                'gioi_tinh' => 1,
                'dia_chi' => '369 Nguyễn Thị Minh Khai, Quận 1, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Đặng Thị Ngọc',
                'email' => 'dangthingoc@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234026',
                'ngay_sinh' => '1992-06-12',
                'gioi_tinh' => 0,
                'dia_chi' => '147 Điện Biên Phủ, Quận Bình Thạnh, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Lý Văn Tài',
                'email' => 'lyvantai@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234027',
                'ngay_sinh' => '1984-03-30',
                'gioi_tinh' => 1,
                'dia_chi' => '258 Cách Mạng Tháng 8, Quận 10, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Trịnh Thị Hương',
                'email' => 'trinhthihuong@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234028',
                'ngay_sinh' => '1989-08-22',
                'gioi_tinh' => 0,
                'dia_chi' => '369 Lê Văn Việt, Quận 9, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Võ Văn Thành',
                'email' => 'vovanthanh@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234029',
                'ngay_sinh' => '1986-01-15',
                'gioi_tinh' => 1,
                'dia_chi' => '147 Phan Văn Trị, Quận 5, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Đỗ Thị Nga',
                'email' => 'dothinga@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234030',
                'ngay_sinh' => '1991-10-07',
                'gioi_tinh' => 0,
                'dia_chi' => '258 Nguyễn Văn Cừ, Quận 1, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Phạm Văn Dũng',
                'email' => 'phamvandung@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234031',
                'ngay_sinh' => '1983-05-20',
                'gioi_tinh' => 1,
                'dia_chi' => '369 Lê Lợi, Quận 1, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Lê Thị Kim',
                'email' => 'lethikim@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234032',
                'ngay_sinh' => '1988-12-15',
                'gioi_tinh' => 0,
                'dia_chi' => '147 Nguyễn Huệ, Quận 1, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Trần Văn Sơn',
                'email' => 'tranvanson@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234033',
                'ngay_sinh' => '1985-08-10',
                'gioi_tinh' => 1,
                'dia_chi' => '258 Đồng Khởi, Quận 1, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Nguyễn Thị Thanh',
                'email' => 'nguyenthanh@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234034',
                'ngay_sinh' => '1990-03-25',
                'gioi_tinh' => 0,
                'dia_chi' => '369 Pasteur, Quận 1, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Hoàng Văn Nam',
                'email' => 'hoangvannam@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234035',
                'ngay_sinh' => '1987-07-18',
                'gioi_tinh' => 1,
                'dia_chi' => '147 Hai Bà Trưng, Quận 1, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Vũ Thị Mai',
                'email' => 'vuthimai@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234036',
                'ngay_sinh' => '1984-11-30',
                'gioi_tinh' => 0,
                'dia_chi' => '258 Điện Biên Phủ, Quận 3, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Đặng Văn Hùng',
                'email' => 'dangvanhung@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234037',
                'ngay_sinh' => '1989-06-12',
                'gioi_tinh' => 1,
                'dia_chi' => '369 Võ Văn Tần, Quận 3, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Lý Thị Hoa',
                'email' => 'lythihoa@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234038',
                'ngay_sinh' => '1986-02-08',
                'gioi_tinh' => 0,
                'dia_chi' => '147 Lý Chính Thắng, Quận 3, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Trịnh Văn Tài',
                'email' => 'trinhvantai@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234039',
                'ngay_sinh' => '1983-09-22',
                'gioi_tinh' => 1,
                'dia_chi' => '258 Trần Quốc Thảo, Quận 3, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Võ Thị Nga',
                'email' => 'vothinga@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234040',
                'ngay_sinh' => '1992-01-14',
                'gioi_tinh' => 0,
                'dia_chi' => '369 Nguyễn Thị Diệu, Quận 3, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Đỗ Văn Minh',
                'email' => 'dovanminh@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234041',
                'ngay_sinh' => '1988-04-28',
                'gioi_tinh' => 1,
                'dia_chi' => '147 Trần Huy Liệu, Quận Phú Nhuận, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Phạm Thị Dung',
                'email' => 'phamthidung@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234042',
                'ngay_sinh' => '1985-10-16',
                'gioi_tinh' => 0,
                'dia_chi' => '258 Phan Xích Long, Quận Phú Nhuận, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Lê Văn Cường',
                'email' => 'levancuong@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234043',
                'ngay_sinh' => '1987-12-05',
                'gioi_tinh' => 1,
                'dia_chi' => '369 Nguyễn Văn Trỗi, Quận Phú Nhuận, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Trần Thị Bình',
                'email' => 'tranthibinh@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234044',
                'ngay_sinh' => '1991-07-19',
                'gioi_tinh' => 0,
                'dia_chi' => '147 Hoàng Văn Thụ, Quận Phú Nhuận, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Nguyễn Văn An',
                'email' => 'nguyenvanan@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234045',
                'ngay_sinh' => '1986-03-11',
                'gioi_tinh' => 1,
                'dia_chi' => '258 Lê Văn Sỹ, Quận Phú Nhuận, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Hoàng Thị Mai',
                'email' => 'hoangthimai@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234046',
                'ngay_sinh' => '1989-11-23',
                'gioi_tinh' => 0,
                'dia_chi' => '369 Phan Đình Phùng, Quận Phú Nhuận, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Vũ Hoàng Nam',
                'email' => 'vuhoangnam@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234047',
                'ngay_sinh' => '1984-06-07',
                'gioi_tinh' => 1,
                'dia_chi' => '147 Nguyễn Kiệm, Quận Phú Nhuận, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Đặng Thị Ngọc',
                'email' => 'dangthingoc2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234048',
                'ngay_sinh' => '1990-08-31',
                'gioi_tinh' => 0,
                'dia_chi' => '258 Nguyễn Thị Huỳnh, Quận Phú Nhuận, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Lý Văn Tài',
                'email' => 'lyvantai2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234049',
                'ngay_sinh' => '1987-05-14',
                'gioi_tinh' => 1,
                'dia_chi' => '369 Phan Chu Trinh, Quận Phú Nhuận, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Trịnh Thị Hương',
                'email' => 'trinhthihuong2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234050',
                'ngay_sinh' => '1992-12-18',
                'gioi_tinh' => 0,
                'dia_chi' => '147 Nguyễn Văn Nghi, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Võ Văn Thành',
                'email' => 'vovanthanh2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234051',
                'ngay_sinh' => '1986-09-26',
                'gioi_tinh' => 1,
                'dia_chi' => '258 Quang Trung, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Đỗ Thị Nga',
                'email' => 'dothinga2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234052',
                'ngay_sinh' => '1989-02-13',
                'gioi_tinh' => 0,
                'dia_chi' => '369 Nguyễn Oanh, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Phạm Văn Dũng',
                'email' => 'phamvandung2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234053',
                'ngay_sinh' => '1983-07-29',
                'gioi_tinh' => 1,
                'dia_chi' => '147 Phan Văn Trị, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Lê Thị Kim',
                'email' => 'lethikim2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234054',
                'ngay_sinh' => '1988-01-05',
                'gioi_tinh' => 0,
                'dia_chi' => '258 Lê Đức Thọ, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Trần Văn Sơn',
                'email' => 'tranvanson2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234055',
                'ngay_sinh' => '1985-04-17',
                'gioi_tinh' => 1,
                'dia_chi' => '369 Nguyễn Văn Lượng, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Nguyễn Thị Thanh',
                'email' => 'nguyenthanh2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234056',
                'ngay_sinh' => '1990-11-08',
                'gioi_tinh' => 0,
                'dia_chi' => '147 Nguyễn Thái Sơn, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Hoàng Văn Nam',
                'email' => 'hoangvannam2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234057',
                'ngay_sinh' => '1987-06-21',
                'gioi_tinh' => 1,
                'dia_chi' => '258 Nguyễn Văn Bảo, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Vũ Thị Mai',
                'email' => 'vuthimai2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234058',
                'ngay_sinh' => '1984-10-12',
                'gioi_tinh' => 0,
                'dia_chi' => '369 Nguyễn Văn Nghi, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Đặng Văn Hùng',
                'email' => 'dangvanhung2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234059',
                'ngay_sinh' => '1989-03-30',
                'gioi_tinh' => 1,
                'dia_chi' => '147 Nguyễn Văn Bảo, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Lý Thị Hoa',
                'email' => 'lythihoa2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234060',
                'ngay_sinh' => '1986-08-14',
                'gioi_tinh' => 0,
                'dia_chi' => '258 Nguyễn Thái Sơn, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Trịnh Văn Tài',
                'email' => 'trinhvantai2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234061',
                'ngay_sinh' => '1983-12-25',
                'gioi_tinh' => 1,
                'dia_chi' => '369 Nguyễn Văn Lượng, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Võ Thị Nga',
                'email' => 'vothinga2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234062',
                'ngay_sinh' => '1992-05-07',
                'gioi_tinh' => 0,
                'dia_chi' => '147 Lê Đức Thọ, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Đỗ Văn Minh',
                'email' => 'dovanminh2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234063',
                'ngay_sinh' => '1988-07-19',
                'gioi_tinh' => 1,
                'dia_chi' => '258 Phan Văn Trị, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Phạm Thị Dung',
                'email' => 'phamthidung2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234064',
                'ngay_sinh' => '1985-01-31',
                'gioi_tinh' => 0,
                'dia_chi' => '369 Nguyễn Oanh, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Lê Văn Cường',
                'email' => 'levancuong2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234065',
                'ngay_sinh' => '1987-04-11',
                'gioi_tinh' => 1,
                'dia_chi' => '147 Quang Trung, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Trần Thị Bình',
                'email' => 'tranthibinh2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234066',
                'ngay_sinh' => '1991-09-23',
                'gioi_tinh' => 0,
                'dia_chi' => '258 Nguyễn Văn Nghi, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Nguyễn Văn An',
                'email' => 'nguyenvanan2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234067',
                'ngay_sinh' => '1986-06-15',
                'gioi_tinh' => 1,
                'dia_chi' => '369 Nguyễn Văn Bảo, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Hoàng Thị Mai',
                'email' => 'hoangthimai2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234068',
                'ngay_sinh' => '1989-02-28',
                'gioi_tinh' => 0,
                'dia_chi' => '147 Nguyễn Thái Sơn, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 0,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Vũ Hoàng Nam',
                'email' => 'vuhoangnam2@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'https://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234069',
                'ngay_sinh' => '1984-11-09',
                'gioi_tinh' => 1,
                'dia_chi' => '258 Nguyễn Văn Lượng, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
            [
                'ho_ten' => 'Đặng Thị Ngọc',
                'email' => 'dangthingoc3@example.com',
                'password' => bcrypt('123456'),
                'hinh_anh' => 'hthttps://mekoong.com/wp-content/uploads/2022/11/7158840622999211290-8.jpg',
                'so_dien_thoai' => '0901234070',
                'ngay_sinh' => '1990-03-16',
                'gioi_tinh' => 0,
                'dia_chi' => '369 Lê Đức Thọ, Quận Gò Vấp, TP.HCM',
                'tinh_trang' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
            ],
        ]);
    }
}
